name: basic test for develop branch
on:
  push:
    branches-ignore:
      - "release/**"
jobs:
    test-curl:
      runs-on: ubuntu-latest
      steps:
        - run: curl https://aixon-admin.aixon-stg.appier.info/admin-graphql
